# 保留原有节点
from .nodes import NODE_CLASS_MAPPINGS as NODES_MAIN, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_MAIN
# 导入现有音频节点
from .audioFrameWinSize import NODE_CLASS_MAPPINGS as AUDIO_NODES, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_DISPLAY
# 导入新的 storyboard 节点
from .storyboardNode import NODE_CLASS_MAPPINGS as STORYBOARD_NODES, NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_DISPLAY
from .storyboardNodeFirstFrame import NODE_CLASS_MAPPINGS as STORYBOARD_NODES_FIRST_FRAME, NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_DISPLAY_FIRST_FRAME

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(NODES_MAIN)
NODE_CLASS_MAPPINGS.update(AUDIO_NODES)
NODE_CLASS_MAPPINGS.update(STORYBOARD_NODES)
NODE_CLASS_MAPPINGS.update(STORYBOARD_NODES_FIRST_FRAME)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(DISPLAY_MAIN)
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(STORYBOARD_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(STORYBOARD_DISPLAY_FIRST_FRAME)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

print("[Plugin] all nodes registered:", list(NODE_CLASS_MAPPINGS.keys()))
