from .nodes import NODE_CLASS_MAPPINGS as NODES_MAIN, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_MAIN
from .audioFrameWinSize import NODE_CLASS_MAPPINGS as AUDIO_NODES, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(NODES_MAIN)
NODE_CLASS_MAPPINGS.update(AUDIO_NODES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(DISPLAY_MAIN)
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
